version: "3.4"

services:
  app:
    build: .
    restart: unless-stopped
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 7777:7777
    depends_on:
      - database
    environment:
      - PGPORT=5432
      - PGDATABASE=database
      - PGUSER=username
      - PGPASSWORD=password
      - PGHOST=postgres-database

  database:
    container_name: "postgres-database"
    image: "postgres:14.1"
    restart: "no"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
